server:
  port: 8082

spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      password: 123456
mybatis:
   mapperLocations: classpath:/mapper/*.xml
logging:
 config: classpath:log4j2-local.xml